### ISSUE TITLE
Add sanity test script

### ISSUE THREAD

**Issue by shidong-ai** [doody1986/DNNMark#16]

**Comment by mattsinc** [comment]
What is the goal of your sanity test script?  To run all of the benchmarks with the provided config files?  If so, I've created a script for that and can contribute it back if that would be helpful.

Matt

**Comment by shidong-ai** [comment]
@mattsinc Hi Matt, this is exactly what I need. But I have already added one in the tools folder. You can check it out.
If you have additional functionality, please let me know.
Thanks very much for mentioning it though!

Shi

**Comment by mattsinc** [comment]
I didn't realize one was there ... darn, I wouldn't have spent the time writing one then.  It looks like your script has similar functionality to mine.  Mine takes an input arg for debuginfo to allow the user the option of quiet runs, but otherwise what you've added should do the same thing as mine.

What is the warmup flag?  I have not seen that documented anywhere, or used anywhere?

Matt

**Comment by shidong-ai** [comment]
@mattsinc 
I just added that script today. So it wasn't a waste of time for you after all. :)
The warmup flag is only useful if you added warm up phase in the benchmark. The only benchmark that uses this flag is test_alexnet. You can find it in the code.

Shi

**Comment by shidong-ai** [comment]
I added the usage of "warmup" flag in the document.

Shi

**Comment by mattsinc** [comment]
Got it, thanks.

Matt
